spring:
  config:
    import: classpath:application-secret.yml

  application:
    name: job-connect

  profiles:
    active: secret

  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.user}
    password: ${db.pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.trading.dto

server:
  port: 8081